language: android
dist: trusty
apt_packages:
  - imagemagick
android:
  components:
    - build-tools-29.0.2
    - android-29
    - add-on
    - extra
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - openssl aes-256-cbc -K $encrypted_cc21b8817197_key -iv $encrypted_cc21b8817197_iv -in sec/android.keystore.enc -out sec/android.keystore -d
  - nvm install 12
  - node --version
  - npm --version
  - gradle --version
install:
  - npm install
  - npm run icons
  - cd src-cordova
  - npm install
  - npm run prepare:cordova
  - cd ..
script:
  - npm run lint
  - npm test
  - node build-professors-list.js > src/data/professors.json
  - npm run build:webext
  - cd src-cordova
  - npm run build:cordova:android
  - cd ..
before_deploy:
  - npm run sign:webext
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  api_key:
    secure: u0xTJ5thHLlFV92ayfQSS+Xcis0pvKCUWZ9Mk2AxW7iZlIIvDuC5yb4FV+IG5lDWLl5oeTrDDpzhzXSquf0uWYhMWaKWtsQlX5kJ2Oatm6YvnleIQPWOL7cbmeaRLTMOzrKmLVXEGpyNcNtpQ3FAbujm3nPLEGms37SHzkQjuuhqvFDVclLLBS7j7qKNFJod06AsesDQXiq5+df263+Fxhnvc/VFt3PlppIwWvIMhISycTpFhzZPbT066grzHinGcy7h/BZfqHBz1ZrJfG7jInonWY5MEJ6VU0OnhBQ2H7QBO87g+Qt4Vp09FfbGaIUO/wRPuFlqPS8Kd6NzgOLTaTJ3sCvp8ti8xrgg+cXOqVr7tZfc6GW3YRjA0KIOOUOH10qsHa5VHqTMlFZGK0bsAO/KxKmE343yBTJ3QUkQb1I9ZqWngOwZcilTtle8ce9jSkM9b3C+Tija5BO5cDnUwfeEZjG+Zk5L7PyMPhmIQgMfXsa0pBQ+LA0f60B5cRhW88evOOAopLnjn/t/IMte2dHgNihbhIZnOhEQAWjYVLZn8lux0c2w9vhYxLZj712gAiECBZEeEFLtG9cMtp/ehaWrJPmNc415/6sjOG/bAMAhKQZ5IgzpEEq+tzVbK5UwoWhrzDSMm/1Wdd5Zg8aC8LnYSxCuZxuqb2WPq4Q/bzY=
  file:
    - dist/web-ext-artifacts/*.xpi
    - src-cordova/platforms/android/app/build/outputs/apk/release/app-release.apk
  on:
    repo: hft-app/native
    tags: true
