import {library} from '@fortawesome/fontawesome-svg-core';
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';

import {
  faHome,
  faIdBadge,
  faLock,
  faUtensils,
  faClock,
  faCalendar,
  faGraduationCap,
  faBars,
  faSyncAlt,
  faChevronLeft,
  faChevronRight,
  faInfoCircle,
  faHandshake,
  faBullhorn,
  faShieldAlt,
  faPuzzlePiece,
  faStar,
  faShareAlt,
  faBook,
  faLightbulb,
  faListUl,
  faPrint,
  faEnvelope,
  faRss,
  faPhone,
  faSearch,
  faMapMarkerAlt,
  faFileAlt,
  faFont,
  faHistory,
  faArrowLeft,
  faCalendarAlt,
  faTimes,
  faCheck,
  faFolderOpen,
  faChevronDown,
  faChevronUp,
  faCalendarPlus,
  faUserAlt,
  faMoneyCheckAlt,
  faThumbsUp,
  faAddressCard,
  faExclamationTriangle
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faIdBadge,
  faLock,
  faHome,
  faUtensils,
  faClock,
  faCalendar,
  faGraduationCap,
  faBars,
  faSyncAlt,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faInfoCircle,
  faHandshake,
  faBullhorn,
  faShieldAlt,
  faPuzzlePiece,
  faStar,
  faShareAlt,
  faBook,
  faLightbulb,
  faListUl,
  faPrint,
  faEnvelope,
  faRss,
  faPhone,
  faSearch,
  faMapMarkerAlt,
  faFileAlt,
  faFont,
  faHistory,
  faArrowLeft,
  faCalendarAlt,
  faCheck,
  faTimes,
  faFolderOpen,
  faCalendarPlus,
  faUserAlt,
  faMoneyCheckAlt,
  faThumbsUp,
  faAddressCard,
  faExclamationTriangle
);


export default {
  install(Vue) {
    Vue.component('fa-icon', FontAwesomeIcon);
  }
}
